# Generated by Django 6.0.7 on 2026-07-28 08:19

import apps.core.image_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                upload_to="avatars/",
                validators=[apps.core.image_validators.validate_uploaded_image],
            ),
        ),
    ]
