# Generated by Django 6.0.7 on 2026-07-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_editorial_domain"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
    ]
