# Generated by Django 6.0.7 on 2026-07-28 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_category_options_alter_comment_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at"],
                "permissions": [("moderate_comment", "Can moderate comments")],
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("visible", "Visible"),
                    ("withdrawn", "Withdrawn by author"),
                    ("hidden", "Hidden by moderator"),
                ],
                default="visible",
                max_length=10,
            ),
        ),
    ]
