# Generated by Django 6.0.7 on 2026-07-28 07:57

from django.db import migrations


def preserve_inactive_comments(apps, schema_editor):
    Comment = apps.get_model("posts", "Comment")
    Comment.objects.filter(is_active=False).update(visibility="hidden")


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_comment_options_comment_moderated_at_and_more"),
    ]

    operations = [
        migrations.RunPython(preserve_inactive_comments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="comment",
            name="is_active",
        ),
    ]
