# Generated by Django 6.0.7 on 2026-07-28 08:19

import apps.core.image_validators
import apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_remove_comment_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="categories/",
                validators=[apps.core.image_validators.validate_uploaded_image],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                upload_to=apps.posts.models.post_image_path,
                validators=[apps.core.image_validators.validate_uploaded_image],
            ),
        ),
    ]
